export const CONTRACT_CONFIG = {
  address: "0x63b4889Ddf3e7889f39dAe1Cbd467D824b340cea" as const,
  chainId: 11155111, // Ethereum Sepolia
  ruleId: "0xe16b6427c2c18a12b5c1b0d016860ab0caad2ba3749a30e220c1adea8667fe3a" as const,
};

export const CASHBACK_MANAGER_ABI = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyPaused", type: "error" },
  { inputs: [], name: "EnforcedPause", type: "error" },
  { inputs: [], name: "ExpectedPause", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "requested", type: "uint256" },
      { internalType: "uint256", name: "available", type: "uint256" },
    ],
    name: "InsufficientFunds",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint256", name: "percentage", type: "uint256" }],
    name: "InvalidPercentage",
    type: "error",
  },
  { inputs: [], name: "InvalidValidityWindow", type: "error" },
  { inputs: [], name: "LimitExceeded", type: "error" },
  { inputs: [], name: "NotPaused", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "RuleExpired", type: "error" },
  { inputs: [], name: "RuleInactive", type: "error" },
  { inputs: [], name: "RuleNotFound", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  { inputs: [], name: "ZeroAddress", type: "error" },
  { inputs: [], name: "ZeroAmount", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "oldAdmin", type: "address" },
      { indexed: true, internalType: "address", name: "newAdmin", type: "address" },
    ],
    name: "AdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: true, internalType: "bytes32", name: "ruleId", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "transactionValue", type: "uint256" },
    ],
    name: "CashbackDistributed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "admin", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "FundsWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "ruleId", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "percentage", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "cap", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "cumulativeLimit", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "validFrom", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "validUntil", type: "uint256" },
    ],
    name: "RuleRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "account", type: "address" }],
    name: "Unpaused",
    type: "event",
  },
  {
    inputs: [],
    name: "MAX_PERCENTAGE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "admin",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "ruleId", type: "bytes32" },
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "calculateCashback",
    outputs: [{ internalType: "uint256", name: "cashback", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ruleId", type: "bytes32" }],
    name: "getRule",
    outputs: [
      { internalType: "uint256", name: "percentage", type: "uint256" },
      { internalType: "uint256", name: "cap", type: "uint256" },
      { internalType: "uint256", name: "cumulativeLimit", type: "uint256" },
      { internalType: "uint256", name: "validFrom", type: "uint256" },
      { internalType: "uint256", name: "validUntil", type: "uint256" },
      { internalType: "bool", name: "active", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserUsage",
    outputs: [
      { internalType: "uint256", name: "totalReceived", type: "uint256" },
      { internalType: "uint256", name: "transactionCount", type: "uint256" },
      { internalType: "uint256", name: "lastUpdated", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "ruleId", type: "bytes32" }],
    name: "processTransaction",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "percentage", type: "uint256" },
      { internalType: "uint256", name: "cap", type: "uint256" },
      { internalType: "uint256", name: "cumulativeLimit", type: "uint256" },
      { internalType: "uint256", name: "validityWindow", type: "uint256" },
    ],
    name: "registerRule",
    outputs: [{ internalType: "bytes32", name: "ruleId", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "rules",
    outputs: [
      { internalType: "uint256", name: "percentage", type: "uint256" },
      { internalType: "uint256", name: "cap", type: "uint256" },
      { internalType: "uint256", name: "cumulativeLimit", type: "uint256" },
      { internalType: "uint256", name: "validFrom", type: "uint256" },
      { internalType: "uint256", name: "validUntil", type: "uint256" },
      { internalType: "bool", name: "active", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newAdmin", type: "address" }],
    name: "transferAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "userUsage",
    outputs: [
      { internalType: "uint256", name: "totalReceived", type: "uint256" },
      { internalType: "uint256", name: "transactionCount", type: "uint256" },
      { internalType: "uint256", name: "lastUpdated", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "withdrawFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
